/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Supplier;
import model.Supplierdirectory;
import ui.admin.AdminWorkAreaJPanel;
import ui.supplier.SupplierWorkAreaJPanel;


/**
 *
 * @author manasvini
 */
public class Loginscreen extends javax.swing.JPanel {
    
    JPanel mainWorkArea;
    Supplierdirectory supplierDirectory;
    Supplier selectedSupplier = null;

    /**
     * Creates new form Loginscreen
     */
    public Loginscreen(JPanel mainWorkArea, Supplierdirectory supplierDirectory) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.supplierDirectory = supplierDirectory;
        
        populateRoleCombo();
        populateSupplierCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        lblSupplier = new javax.swing.JLabel();
        cmbSuppliers = new javax.swing.JComboBox<>();
        BTNLogin = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LOGIN SCREEN");

        lblRole.setText("Choose Role");

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });

        lblSupplier.setText("Select Supplier");

        cmbSuppliers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppliersActionPerformed(evt);
            }
        });

        BTNLogin.setText("Login");
        BTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplier))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNLogin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbRoles, 0, 170, Short.MAX_VALUE)
                        .addComponent(cmbSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRole, lblSupplier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(BTNLogin)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateSupplierVisibility();
    }//GEN-LAST:event_cmbRolesActionPerformed

    private void cmbSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppliersActionPerformed
        // TODO add your handling code here:
        if(cmbSuppliers.getSelectedItem () == null) return;
        selectedSupplier = (Supplier) cmbSuppliers.getselectedItem () ;
    }//GEN-LAST:event_cmbSuppliersActionPerformed

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = (JPanel) cmbRoles. getSelectedItem();
        if (selectedPanel. getClass () == SupplierWorkAreaJPanel.class) {
                if (selectedSupplier == null) {
           JOptionPane. showMessageDialog(this, "Please select a supplier to login under supplier role.") ;
                return;}
           else {
               selectedPanel = new SupplierWorkAreaJPanel (mainWorkArea, selectedSupplier) ;}
               mainWorkArea. add ("WordAreaJPanel", selectedPanel) ;
               CardLayout layout = (CardLayout) mainWorkArea. getLayout () ;
               layout. next (mainWorkArea) ;
    }//GEN-LAST:event_BTNLoginActionPerformed

    private void populateRoleCombo() {
        cmbRoles.removeAllItems () ;
        AdminWorkAreaJPanel adminPanel = new AdminWorkAreaJPanel (mainWorkArea, supplierDirectory) ;
        SupplierWorkAreaJPanel supplierPanel = new SupplierWorkAreaJPanel (mainWorkArea, selectedSupplier) ;
        cmbRoles. addItem (adminPanel) ; cmbRoles .addItem (supplierPanel) ;
    }

    public void populateSupplierCombo() {
        cmbSuppliers. removeAllItems () ;
        for (Supplier supplier: supplierDirectory getSupplierList ()) {

        cmbSuppliers.addItem (supplier) ;}
    }
    
    private void updateSupplierVisibility(){
      if ( (cmbRoles .getSelectedItem () == null) || (cmbRoles.getSelectedItem() •getClass () == AdminWorkAreaJPanel.class)) {
      selectedSupplier = null;
      lblSupplier. setVisible (false) ; 
      cmbSuppliers. setVisible (false) ;
      return;
    }
      if(cmbRoles.getSelectedItem () -getClass () == SupplierWorkAreaJPanel.class) (
      lblSupplier. setVisible (true) ; 
      cmbSuppliers. setvisible (true) ;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLogin;
    private javax.swing.JComboBox<String> cmbRoles;
    private javax.swing.JComboBox<String> cmbSuppliers;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}

