/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.VitalSignsHistory;
import model.VitalSigns;


/**
 *
 * @author manasvini
 */
public class CreatePanel extends javax.swing.JPanel {
    VitalSignsHistory VitalSignsHistory;

    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(VitalSignsHistory VitalSignsHistory) {
        initComponents();
        this.VitalSignsHistory = VitalSignsHistory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label = new javax.swing.JLabel();
        labtemp = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        labbloodpressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        labpluse = new javax.swing.JLabel();
        txtpluse = new javax.swing.JTextField();
        labdate = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        bnsave = new javax.swing.JButton();

        Label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Create Vital Sings");

        labtemp.setText("Temperature");

        labbloodpressure.setText("Blood Pressure");

        labpluse.setText("Pulse");

        labdate.setText("Date");

        bnsave.setText("Save");
        bnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labpluse)
                        .addGap(18, 18, 18)
                        .addComponent(txtpluse, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labbloodpressure)
                            .addGap(18, 18, 18)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labtemp)
                            .addGap(18, 18, 18)
                            .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labdate)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnsave)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labbloodpressure, labdate, labpluse, labtemp, txtBloodPressure, txtTemperature, txtdate, txtpluse});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labtemp)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labbloodpressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labpluse)
                    .addComponent(txtpluse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labdate)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bnsave)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsaveActionPerformed
        // TODO add your handling code here:
        Double temperature = Double.parseDouble(txtTemperature.getText());
        Double bloodpressure = Double.parseDouble(txtBloodPressure.getText());
        int pluse = Integer.parseInt(txtpluse.getText());
        String date = txtdate.getText();
        
        VitalSigns newvs = VitalSignsHistory.addnewvitalsigns();
        newvs.setTemperature(temperature);
        newvs.setBloodPressure(bloodpressure);
        newvs.setPulse(pluse);
        newvs.setDate(date);
        //show confirmation dialogue
        JOptionPane.showMessageDialog(this, "New vital created" , "Success" , JOptionPane.INFORMATION_MESSAGE);
        
        txtTemperature.setText("");
        txtBloodPressure.setText("");
        txtpluse.setText("");
        txtdate.setText("");
        
        
        
    }//GEN-LAST:event_bnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton bnsave;
    private javax.swing.JLabel labbloodpressure;
    private javax.swing.JLabel labdate;
    private javax.swing.JLabel labpluse;
    private javax.swing.JLabel labtemp;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtpluse;
    // End of variables declaration//GEN-END:variables
}
